- name: Start Minikube
  command: minikube start

- name: Enable ingress addon (optional for later)
  command: minikube addons enable ingress
  ignore_errors: yes

- name: Create Kubernetes deployment
  template:
    src: ghost-deployment.yaml.j2
    dest: /tmp/ghost-deployment.yaml

- name: Apply Kubernetes deployment
  command: kubectl apply -f /tmp/ghost-deployment.yaml

